# docker-compose.yml

version: "3.5"

volumes:
  elk:
    name: elk

services:

  es:
    container_name: es
    image: es_image
    restart: unless-stopped
    labels:
      - traefik.enable=false
    volumes:
      - elk:/home/user/
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash_image
    restart: unless-stopped
    labels:
      - traefik.enable=false
    networks:
      - elk
    
networks:
#  public-web:
#    external: true
  elk:
    name: elk
